---
driver:
  name: docker
  command: ${MOLECULE_DOCKER_COMMAND:-""}
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: true
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: debian9
    image: geerlingguy/docker-debian9-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: centos8
    image: geerlingguy/docker-centos8-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
  - name: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ../../..
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
  #  - verify # testinfra dies on pytest for some reason
    - destroy
verifier:
  name: testinfra
  line: flake8
  options:
    verbose: true

